use retry to fight flakyness

diff --git a/.github/workflows/tox.yml b/.github/workflows/tox.yml
--- a/.github/workflows/tox.yml
+++ b/.github/workflows/tox.yml
@@ -75,8 +75,6 @@ jobs:
         run: |
           sudo apt-get update
 
-
-
       - name: Install docker
         run: |
           . /etc/os-release
@@ -97,7 +95,6 @@ jobs:
           curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.9.0/kind-$(uname)-amd64" && chmod +x ./kind
           sudo install kind /usr/local/bin
         if: ${{ contains(matrix.tox_env, 'py') }}
-
 
       - name: Enable ipv4 and ipv6 forwarding
         run: |
@@ -196,51 +193,64 @@ jobs:
         run: |
           # Service Account for Job
           sudo kubectl create -f tools/test-rolebinding.yaml
-          # Configmap will be witinig untill it is deleted, telling one Pod ended the Job
-          sudo kubectl create configmap molecule-job-running --from-literal status=Started
         if: ${{ contains(matrix.tox_env, 'py') }}
 
-      - name: Start test Job
-        run: |
-          cat <<EOF | sudo kubectl apply -f -
-          ---
-          apiVersion: batch/v1
-          kind: Job
-          metadata:
-            name: molecule
-          spec:
-            template:
-              spec:
-                serviceAccountName: molecule-kubevirt
-                containers:
-                - name: molecule
-                  image: molecule_kubevirt_${{ matrix.tox_env }}
-                  imagePullPolicy: IfNotPresent
-                  command: [ "/bin/bash", "-c", "--" ]
-                  args: ["(tox -e ${{ matrix.tox_env }} -c /opt/molecule_kubevirt/tox.ini ; kubectl create configmap molecule-result --from-literal exitCode=\$?); kubectl delete configmap molecule-job-running"]
-                  env:
-                    - name: PYTEST_REQPASS
-                      value: "2"
-                restartPolicy: Never
-            backoffLimit: 0
-          EOF
-
-          echo "Job launched"
-        if: ${{ contains(matrix.tox_env, 'py') }}
-
-      - name: Wait for Job to end and log Pods in default namespace
+      - name: Launch background log scripts
         run: |
           # Kail monitor any logs from default namespace
           sudo kail -n default 2>&1 | tee /tmp/kail.log &
-          # Wait for molecule Job Pod to start
-          sudo kubectl wait --for=condition=ready pods -l job-name=molecule --namespace default
-          # Launch virtctl console log script in backgroung
           (sudo tools/log_console.sh || true ) &
-          # Wait for molecule Job to delete configmap, notifying one Job Pod ran till the end, whatever the result
-          sudo kubectl wait --for delete --timeout=20m  configmap/molecule-job-running
-          # Get molecule tests results
-          MOLECULE_RESULT=$(sudo kubectl get configmap molecule-result -o "jsonpath={.data['exitCode']}")
-          if [ ! "${MOLECULE_RESULT}" == "0" ]; then echo "Test non ok : ${MOLECULE_RESULT}"; exit 1; fi
+
+      - name: Launch test
+        uses: nick-invision/retry@v2
+        with:
+          timeout_minutes: 25
+          max_attempts: 3
+          on_retry_command: |
+            echo "ERROR !!! retrying"
+            sudo kubectl delete pods --all || true
+            sudo kubectl delete configmaps --all || true
+            sudo kubectl delete job --all || true
+          command: |
+            # Configmap will be waitinig untill it is deleted, telling one Pod ended the Job
+            sudo kubectl create configmap molecule-job-running --from-literal status=Started
+            cat <<EOF | sudo kubectl apply -f -
+            ---
+            apiVersion: batch/v1
+            kind: Job
+            metadata:
+              name: molecule
+            spec:
+              template:
+                spec:
+                  serviceAccountName: molecule-kubevirt
+                  containers:
+                  - name: molecule
+                    image: molecule_kubevirt_${{ matrix.tox_env }}
+                    imagePullPolicy: IfNotPresent
+                    command: [ "/bin/bash", "-c", "--" ]
+                    args: ["(tox -e ${{ matrix.tox_env }} -c /opt/molecule_kubevirt/tox.ini ; kubectl create configmap molecule-result --from-literal exitCode=\$?); kubectl delete configmap molecule-job-running"]
+                    env:
+                      - name: PYTEST_REQPASS
+                        value: "2"
+                  restartPolicy: Never
+              backoffLimit: 0
+            EOF
+
+            echo "Job launched"
+
+            # Wait for molecule Job Pod to start
+            until (sudo kubectl get pods -l job-name=molecule | grep molecule); do echo "Wait molecule pod to start"; sleep 5; done
+
+            sudo kubectl wait --for=condition=ready pods -l job-name=molecule --namespace default
+            echo "Molecule pod is now running, waiting..."
+
+            # Wait for molecule Job to delete configmap, notifying one Job Pod ran till the end, whatever the result
+            sudo kubectl wait --for delete --timeout=20m  configmap/molecule-job-running
+
+            # Get molecule tests results and exit accordingly
+            MOLECULE_RESULT=$(sudo kubectl get configmap molecule-result -o "jsonpath={.data['exitCode']}")
+            if [ ! "${MOLECULE_RESULT}" == "0" ]; then echo "Test non ok : ${MOLECULE_RESULT}"; exit 1; fi
         if: ${{ contains(matrix.tox_env, 'py') }}
 
       - name: Dump and export logs
